version: "3.8"

services:
  auth_app:
    build:
      context:
        .
    volumes:
      - ./src:/app
    env_file:
      - .env
    command: ['uvicorn', 'main:app', '--reload', '--host', '0.0.0.0', '--port', '8000']
    ports:
      - "80:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
