version: "3.8"

services:
  auth_app:
    build:
      context:
        .
    volumes:
      - ./src:/app
    env_file:
      - .env
    command: ['python', 'main.py']
    ports:
      - "80:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:15.3
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:7.8
    env_file:
      - .env
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
